START TRANSACTION;



-- Table structure for table `ASCountry`
CREATE TABLE `ASCountry` (
 `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
 `asn` int(11) NOT NULL COMMENT 'AS番号',
 `country` char(2) NOT NULL COMMENT '国コード',
 `rir` enum('apnic','arin','ripencc','lacnic','afrinic') NOT NULL COMMENT '地域レジストリ',
 `date_since` date NOT NULL COMMENT '日時（開始日）',
 `date_until` date NOT NULL COMMENT '日時（終了日）',
 PRIMARY KEY (`id`),
 KEY `date_until` (`date_until`,`date_since`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ASと国の紐付け情報';



-- Table structure for table `ConflictAsnWhiteList`
CREATE TABLE `ConflictAsnWhiteList` (
 `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
 `conflict_type` tinyint(4) NOT NULL COMMENT '例外の種類',
 `asn` int(10) unsigned NOT NULL COMMENT 'ハイジャックAS番号',
 `conflict_asn` int(10) unsigned NOT NULL COMMENT '被ハイジャックAS番号',
 `date_register` datetime NOT NULL DEFAULT current_timestamp() COMMENT '登録日',
 `disabled` datetime DEFAULT NULL COMMENT '無効化フラグ',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ASレベルのホワイトリスト';



-- Table structure for table `ConflictCountryWhiteList`
CREATE TABLE `ConflictCountryWhiteList` (
 `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
 `conflict_type` tinyint(4) NOT NULL COMMENT '例外の種類',
 `cc` char(2) NOT NULL COMMENT '国コード（ハイジャック側）',
 `conflict_cc` char(2) NOT NULL COMMENT '国コード（被ハイジャック側）',
 PRIMARY KEY (`id`),
 KEY `country` (`cc`,`conflict_cc`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='国レベルのホワイトリスト';



-- Table structure for table `CountryInfo`
CREATE TABLE `CountryInfo` (
 `cc` char(2) NOT NULL COMMENT '国コード',
 `country_name` varchar(255) NOT NULL COMMENT '国名',
 `rir` enum('apnic','arin','ripencc','lacnic','afrinic','other') NOT NULL COMMENT '所属RIR',
 PRIMARY KEY (`cc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='国情報';

-- data
INSERT INTO `CountryInfo` (`cc`, `country_name`, `rir`) VALUES
('AD', 'ANDORRA', 'ripencc'),
('AE', 'UNITED ARAB EMIRATES', 'ripencc'),
('AF', 'AFGHANISTAN', 'apnic'),
('AG', 'ANTIGUA AND BARBUDA', 'arin'),
('AI', 'ANGUILLA', 'arin'),
('AL', 'ALBANIA', 'ripencc'),
('AM', 'ARMENIA', 'ripencc'),
('AO', 'ANGOLA', 'afrinic'),
('AQ', 'ANTARCTICA', 'arin'),
('AR', 'ARGENTINA', 'lacnic'),
('AS', 'AMERICAN SAMOA', 'apnic'),
('AT', 'AUSTRIA', 'ripencc'),
('AU', 'AUSTRALIA', 'apnic'),
('AW', 'ARUBA', 'lacnic'),
('AX', 'ÅLAND ISLANDS', 'ripencc'),
('AZ', 'AZERBAIJAN', 'ripencc'),
('BA', 'BOSNIA AND HERZEGOWINA', 'ripencc'),
('BB', 'BARBADOS', 'arin'),
('BD', 'BANGLADESH', 'apnic'),
('BE', 'BELGIUM', 'ripencc'),
('BF', 'BURKINA FASO', 'afrinic'),
('BG', 'BULGARIA', 'ripencc'),
('BH', 'BAHRAIN', 'ripencc'),
('BI', 'BURUNDI', 'afrinic'),
('BJ', 'BENIN', 'afrinic'),
('BL', 'SAINT BARTHÉLEMY', 'arin'),
('BM', 'BERMUDA', 'arin'),
('BN', 'BRUNEI DARUSSALAM', 'apnic'),
('BO', 'BOLIVIA, PLURINATIONAL STATE OF', 'lacnic'),
('BQ', 'BONAIRE, SINT EUSTATIUS AND SABA', 'lacnic'),
('BR', 'BRAZIL', 'lacnic'),
('BS', 'BAHAMAS', 'arin'),
('BT', 'BHUTAN', 'apnic'),
('BV', 'BOUVET ISLAND', 'arin'),
('BW', 'BOTSWANA', 'afrinic'),
('BY', 'BELARUS', 'ripencc'),
('BZ', 'BELIZE', 'lacnic'),
('CA', 'CANADA', 'arin'),
('CC', 'COCOS (KEELING) ISLANDS', 'apnic'),
('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'afrinic'),
('CF', 'CENTRAL AFRICAN REPUBLIC', 'afrinic'),
('CG', 'CONGO', 'afrinic'),
('CH', 'SWITZERLAND', 'ripencc'),
('CI', 'COTE D\'IVOIRE', 'afrinic'),
('CK', 'COOK ISLANDS', 'apnic'),
('CL', 'CHILE', 'lacnic'),
('CM', 'CAMEROON', 'afrinic'),
('CN', 'CHINA', 'apnic'),
('CO', 'COLOMBIA', 'lacnic'),
('CR', 'COSTA RICA', 'lacnic'),
('CU', 'CUBA', 'lacnic'),
('CV', 'CAPE VERDE', 'afrinic'),
('CW', 'CURAÇAO', 'lacnic'),
('CX', 'CHRISTMAS ISLAND', 'apnic'),
('CY', 'CYPRUS', 'ripencc'),
('CZ', 'CZECHIA', 'ripencc'),
('DE', 'GERMANY', 'ripencc'),
('DJ', 'DJIBOUTI', 'afrinic'),
('DK', 'DENMARK', 'ripencc'),
('DM', 'DOMINICA', 'arin'),
('DO', 'DOMINICAN REPUBLIC', 'lacnic'),
('DZ', 'ALGERIA', 'afrinic'),
('EC', 'ECUADOR', 'lacnic'),
('EE', 'ESTONIA', 'ripencc'),
('EG', 'EGYPT', 'afrinic'),
('EH', 'WESTERN SAHARA', 'afrinic'),
('ER', 'ERITREA', 'afrinic'),
('ES', 'SPAIN', 'ripencc'),
('ET', 'ETHIOPIA', 'afrinic'),
('FI', 'FINLAND', 'ripencc'),
('FJ', 'FIJI', 'apnic'),
('FK', 'FALKLAND ISLANDS (MALVINAS)', 'lacnic'),
('FM', 'MICRONESIA, FEDERATED STATES OF', 'apnic'),
('FO', 'FAROE ISLANDS', 'ripencc'),
('FR', 'FRANCE', 'ripencc'),
('GA', 'GABON', 'afrinic'),
('GB', 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND*', 'ripencc'),
('GD', 'GRENADA', 'arin'),
('GE', 'GEORGIA', 'ripencc'),
('GF', 'FRENCH GUIANA', 'lacnic'),
('GG', 'GUERNSEY', 'ripencc'),
('GH', 'GHANA', 'afrinic'),
('GI', 'GIBRALTAR', 'ripencc'),
('GL', 'GREENLAND', 'ripencc'),
('GM', 'GAMBIA', 'afrinic'),
('GN', 'GUINEA', 'afrinic'),
('GP', 'GUADELOUPE', 'arin'),
('GQ', 'EQUATORIAL GUINEA', 'afrinic'),
('GR', 'GREECE', 'ripencc'),
('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'lacnic'),
('GT', 'GUATEMALA', 'lacnic'),
('GU', 'GUAM', 'apnic'),
('GW', 'GUINEA-BISSAU', 'afrinic'),
('GY', 'GUYANA', 'lacnic'),
('HK', 'HONG KONG', 'apnic'),
('HM', 'HEARD AND MC DONALD ISLANDS', 'arin'),
('HN', 'HONDURAS', 'lacnic'),
('HR', 'CROATIA (local name: Hrvatska)', 'ripencc'),
('HT', 'HAITI', 'lacnic'),
('HU', 'HUNGARY', 'ripencc'),
('ID', 'INDONESIA', 'apnic'),
('IE', 'IRELAND', 'ripencc'),
('IL', 'ISRAEL', 'ripencc'),
('IM', 'ISLE OF MAN', 'ripencc'),
('IN', 'INDIA', 'apnic'),
('IO', 'BRITISH INDIAN OCEAN TERRITORY', 'apnic'),
('IQ', 'IRAQ', 'ripencc'),
('IR', 'IRAN (ISLAMIC REPUBLIC OF)', 'ripencc'),
('IS', 'ICELAND', 'ripencc'),
('IT', 'ITALY', 'ripencc'),
('JE', 'JERSEY', 'ripencc'),
('JM', 'JAMAICA', 'arin'),
('JO', 'JORDAN', 'ripencc'),
('JP', 'JAPAN', 'apnic'),
('KE', 'KENYA', 'afrinic'),
('KG', 'KYRGYZSTAN', 'ripencc'),
('KH', 'CAMBODIA', 'apnic'),
('KI', 'KIRIBATI', 'apnic'),
('KM', 'COMOROS', 'afrinic'),
('KN', 'SAINT KITTS AND NEVIS', 'arin'),
('KP', 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'apnic'),
('KR', 'KOREA, REPUBLIC OF', 'apnic'),
('KW', 'KUWAIT', 'ripencc'),
('KY', 'CAYMAN ISLANDS', 'arin'),
('KZ', 'KAZAKHSTAN', 'ripencc'),
('LA', 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'apnic'),
('LB', 'LEBANON', 'ripencc'),
('LC', 'SAINT LUCIA', 'arin'),
('LI', 'LIECHTENSTEIN', 'ripencc'),
('LK', 'SRI LANKA', 'apnic'),
('LR', 'LIBERIA', 'afrinic'),
('LS', 'LESOTHO', 'afrinic'),
('LT', 'LITHUANIA', 'ripencc'),
('LU', 'LUXEMBOURG', 'ripencc'),
('LV', 'LATVIA', 'ripencc'),
('LY', 'LIBYA', 'afrinic'),
('MA', 'MOROCCO', 'afrinic'),
('MC', 'MONACO', 'ripencc'),
('MD', 'MOLDOVA, REPUBLIC OF', 'ripencc'),
('ME', 'MONTENEGRO', 'ripencc'),
('MF', 'SAINT MARTIN (FRENCH PART)', 'arin'),
('MG', 'MADAGASCAR', 'afrinic'),
('MH', 'MARSHALL ISLANDS', 'apnic'),
('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'ripencc'),
('ML', 'MALI', 'afrinic'),
('MM', 'MYANMAR', 'apnic'),
('MN', 'MONGOLIA', 'apnic'),
('MO', 'MACAO', 'apnic'),
('MP', 'NORTHERN MARIANA ISLANDS', 'apnic'),
('MQ', 'MARTINIQUE', 'arin'),
('MR', 'MAURITANIA', 'afrinic'),
('MS', 'MONTSERRAT', 'arin'),
('MT', 'MALTA', 'ripencc'),
('MU', 'MAURITIUS', 'afrinic'),
('MV', 'MALDIVES', 'apnic'),
('MW', 'MALAWI', 'arin'),
('MX', 'MEXICO', 'lacnic'),
('MY', 'MALAYSIA', 'apnic'),
('MZ', 'MOZAMBIQUE', 'afrinic'),
('NA', 'NAMIBIA', 'afrinic'),
('NC', 'NEW CALEDONIA', 'apnic'),
('NE', 'NIGER', 'afrinic'),
('NF', 'NORFOLK ISLAND', 'apnic'),
('NG', 'NIGERIA', 'afrinic'),
('NI', 'NICARAGUA', 'lacnic'),
('NL', 'NETHERLANDS', 'ripencc'),
('NO', 'NORWAY', 'ripencc'),
('NP', 'NEPAL', 'apnic'),
('NR', 'NAURU', 'apnic'),
('NU', 'NIUE', 'apnic'),
('NZ', 'NEW ZEALAND', 'apnic'),
('OM', 'OMAN', 'ripencc'),
('PA', 'PANAMA', 'lacnic'),
('PE', 'PERU', 'lacnic'),
('PF', 'FRENCH POLYNESIA', 'apnic'),
('PG', 'PAPUA NEW GUINEA', 'apnic'),
('PH', 'PHILIPPINES', 'apnic'),
('PK', 'PAKISTAN', 'apnic'),
('PL', 'POLAND', 'ripencc'),
('PM', 'SAINT PIERRE AND MIQUELON', 'arin'),
('PN', 'PITCAIRN', 'apnic'),
('PR', 'PUERTO RICO', 'arin'),
('PS', 'PALESTINE, STATE OF', 'ripencc'),
('PT', 'PORTUGAL', 'ripencc'),
('PW', 'PALAU', 'apnic'),
('PY', 'PARAGUAY', 'lacnic'),
('QA', 'QATAR', 'ripencc'),
('RE', 'REUNION', 'afrinic'),
('RO', 'ROMANIA', 'ripencc'),
('RS', 'SERBIA', 'ripencc'),
('RU', 'RUSSIAN FEDERATION', 'ripencc'),
('RW', 'RWANDA', 'afrinic'),
('SA', 'SAUDI ARABIA', 'ripencc'),
('SB', 'SOLOMON ISLANDS', 'apnic'),
('SC', 'SEYCHELLES', 'afrinic'),
('SD', 'SUDAN', 'afrinic'),
('SE', 'SWEDEN', 'ripencc'),
('SG', 'SINGAPORE', 'apnic'),
('SH', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', 'arin'),
('SI', 'SLOVENIA', 'ripencc'),
('SJ', 'SVALBARD AND JAN MAYEN ISLANDS', 'ripencc'),
('SK', 'SLOVAKIA', 'ripencc'),
('SL', 'SIERRA LEONE', 'afrinic'),
('SM', 'SAN MARINO', 'ripencc'),
('SN', 'SENEGAL', 'afrinic'),
('SO', 'SOMALIA', 'afrinic'),
('SR', 'SURINAME', 'lacnic'),
('SS', 'SOUTH SUDAN', 'afrinic'),
('ST', 'SAO TOME AND PRINCIPE', 'afrinic'),
('SV', 'EL SALVADOR', 'lacnic'),
('SX', 'SINT MAARTEN (DUTCH PART)', 'lacnic'),
('SY', 'SYRIAN ARAB REPUBLIC', 'ripencc'),
('SZ', 'ESWATINI', 'afrinic'),
('TC', 'TURKS AND CAICOS ISLANDS', 'arin'),
('TD', 'CHAD', 'afrinic'),
('TF', 'FRENCH SOUTHERN TERRITORIES', 'apnic'),
('TG', 'TOGO', 'afrinic'),
('TH', 'THAILAND', 'apnic'),
('TJ', 'TAJIKISTAN', 'ripencc'),
('TK', 'TOKELAU', 'apnic'),
('TL', 'TIMOR-LESTE', 'apnic'),
('TM', 'TURKMENISTAN', 'ripencc'),
('TN', 'TUNISIA', 'afrinic'),
('TO', 'TONGA', 'apnic'),
('TR', 'TURKEY', 'ripencc'),
('TT', 'TRINIDAD AND TOBAGO', 'lacnic'),
('TV', 'TUVALU', 'apnic'),
('TW', 'TAIWAN, PROVINCE OF CHINA', 'apnic'),
('TZ', 'TANZANIA, UNITED REPUBLIC OF', 'afrinic'),
('UA', 'UKRAINE', 'ripencc'),
('UG', 'UGANDA', 'afrinic'),
('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'arin'),
('US', 'UNITED STATES OF AMERICA', 'arin'),
('UY', 'URUGUAY', 'lacnic'),
('UZ', 'UZBEKISTAN', 'ripencc'),
('VA', 'HOLY SEE', 'ripencc'),
('VC', 'SAINT VINCENT AND THE GRENADINES', 'arin'),
('VE', 'VENEZUELA, BOLIVARIAN REPUBLIC OF', 'lacnic'),
('VG', 'VIRGIN ISLANDS (BRITISH)', 'arin'),
('VI', 'VIRGIN ISLANDS (U.S.)', 'arin'),
('VN', 'VIET NAM', 'apnic'),
('VU', 'VANUATU', 'apnic'),
('WF', 'WALLIS AND FUTUNA ISLANDS', 'apnic'),
('WS', 'SAMOA', 'apnic'),
('YE', 'YEMEN', 'ripencc'),
('YT', 'MAYOTTE', 'afrinic'),
('ZA', 'SOUTH AFRICA', 'afrinic'),
('ZM', 'ZAMBIA', 'afrinic'),
('ZW', 'ZIMBABWE', 'afrinic');



-- Table structure for table `CronProgress`
CREATE TABLE `CronProgress` (
 `id` int(11) NOT NULL COMMENT 'id',
 `cron` varchar(191) NOT NULL COMMENT 'Cron名（固定）',
 `name` varchar(191) NOT NULL COMMENT '属性名（固定）',
 `value` varchar(191) NOT NULL COMMENT '値1（可変）',
 `value2` varchar(191) DEFAULT NULL COMMENT '値2（可変）',
 `failed_count` int(11) NOT NULL COMMENT '連続失敗数',
 `max_failed_count` int(11) NOT NULL COMMENT '連続失敗数の閾値',
 `processing` bit(1) NOT NULL COMMENT '実行中フラグ',
 PRIMARY KEY (`id`),
 UNIQUE KEY `cron` (`cron`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='cronの進捗管理';

-- data
INSERT INTO `CronProgress` (`id`, `cron`, `name`, `value`, `value2`, `failed_count`, `max_failed_count`, `processing`) VALUES
(1, 'BGPFullRoute', 'ripe_rc00', '2017-12-31 16:00', '1970-01-01 00:00', 0, 16, b'0'),
(2, 'BGPUpdate', 'ripe_rc00', '2017-12-31 23:55', '2017-12-31 23:55', 0, 16, b'0'),
(3, 'FilterSuspiciousBGPUpdate', '', '', null, 0, 0, b'0'),
(101, 'ASCountry', 'apnic', '2017-12-31', '1970-01-01 00:00:00', 0, 24, b'0'),
(102, 'ASCountry', 'arin', '2017-12-31', '1970-01-01 00:00:00', 0, 24, b'0'),
(103, 'ASCountry', 'ripencc', '2017-12-31', '1970-01-01 00:00:00', 0, 24, b'0'),
(104, 'ASCountry', 'lacnic', '2017-12-31', '1970-01-01 00:00:00', 0, 24, b'0'),
(105, 'ASCountry', 'afrinic', '2017-12-31', '1970-01-01 00:00:00', 0, 24, b'0');



-- Table structure for table `SuspiciousUpdate`
CREATE TABLE `SuspiciousAsnSet` (
 `suspicious_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'suspicious_id',
 `conflict_type` tinyint(4) NOT NULL COMMENT 'conflict_type（1, 10〜）',
 `asn` int(10) unsigned NOT NULL COMMENT '広告したAS',
 `conflict_asn` varchar(191) NOT NULL COMMENT '衝突先AS',
 `asn_cc` char(2) NOT NULL COMMENT '国コード',
 `conflict_asn_cc` varchar(191) NOT NULL COMMENT '衝突先国コード',
 `asn_whois` varchar(191) NOT NULL COMMENT 'whois情報',
 `conflict_asn_whois` varchar(191) NOT NULL COMMENT '衝突先whois情報',
 `date_detection` datetime NOT NULL COMMENT '検知日時',
 PRIMARY KEY (`suspicious_id`),
 UNIQUE KEY `conflict_info` (`asn`,`conflict_asn`,`asn_cc`,`conflict_asn_cc`) USING BTREE,
 KEY `date_detection` (`date_detection`),
 KEY `conflict_type` (`conflict_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='怪しいASの組み合わせ';



-- Table structure for table `PrefixConflictedUpdate`
CREATE TABLE `PrefixConflictedUpdate` (
 `update_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
 `ip_protocol` enum('v4','v6') NOT NULL COMMENT 'v4 or v6',
 `adv_type` tinyint(4) NOT NULL COMMENT 'advertisement_type',
 `asn` int(10) unsigned NOT NULL COMMENT '広告したAS',
 `conflict_asn` varchar(191) NOT NULL COMMENT '衝突先AS',
 `ip_prefix` varchar(24) NOT NULL COMMENT '広告されたIP prefix',
 `conflict_ip_prefix` varchar(24) NOT NULL COMMENT '衝突先IP prefix',
 `date_update` datetime NOT NULL COMMENT '広告された時間',
 `rc` varchar(191) NOT NULL COMMENT 'ルートコレクタ',
 `count` int(10) unsigned NOT NULL DEFAULT 1 COMMENT '重複数',
 `suspicious_id` int(10) unsigned DEFAULT NULL COMMENT 'SuspiciousUpdateのsuspicious_id',
 PRIMARY KEY (`update_id`),
 UNIQUE KEY `confliction` (`asn`,`conflict_asn`,`ip_prefix`,`conflict_ip_prefix`,`rc`) USING BTREE,
 KEY `adv_type` (`adv_type`),
 KEY `suspicious_id` (`suspicious_id`),
 CONSTRAINT `prefixconflictedupdate_ibfk_1` FOREIGN KEY (`suspicious_id`) REFERENCES `SuspiciousAsnSet` (`suspicious_id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IPプレフィックスが衝突しているBGP広告';



-- Table structure for table `Whois`
CREATE TABLE `Whois` (
 `whois_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
 `host` varchar(191) NOT NULL,
 `query` varchar(191) NOT NULL,
 `name` varchar(191) NOT NULL,
 `body` mediumtext NOT NULL,
 `date_query` datetime NOT NULL DEFAULT current_timestamp(),
 PRIMARY KEY (`whois_id`),
 UNIQUE KEY `query` (`query`,`date_query`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='whois情報';



COMMIT;
